---
- name: MAIN TASK | Installing and Configuring KVM Host
  hosts: hypervisor
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
