---
#Installing the Software
- name: installing | installing the required software
  become: yes
  when: (ansible_os_family == 'RHEL')
  yum:
    name:
    - libguestfs-tools
    - libvirt
    - qemu-kvm
    - virt-manager
    - virt-install
    - xorg-x11-apps
    - xauth
    - virt-viewer
    - libguestfs-xfs
    state: latest
  notify: enable_service

- name: installing | installing the required software
  become: yes
  when: (ansible_os_family == 'Debian')
  apt:
    name:
    - libguestfs-tools
    - libvirt-daemon
    - qemu-kvm
    - virt-manager
    - virtinst
    - virt-viewer
    - libguestfs-xfs
    state: latest
  notify: enable_service

  # - name: installing | installing rhel-guest-image for templates
  #   become: yes
  #   yum:
  #     name: "{{ item }}"
  #     state: latest
  #   with_items:
  #     - rhel-guest-image-7
