---
  - name: Wait until reachable
    wait_for_connection:

  - name: Gather facts for first time
    setup:

  - name: register and subscribe to RHN
    redhat_subscription:
      state: present
      username: "{{ rhn_user }}"
      password: "{{ rhn_pass }}"
      auto_attach: true
    become: true

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
    become: true

  - name: install insights-client
    yum:
      name: insights-client
      state: latest
    become: true

  - name: register with insights
    command: redhat-access-insights --register --group {{ domain_name }}
    become: true
